
version: '3'
services:
  app:
    image: mintproject/dash-viz:latest
    restart: on-failure
    env_file:
     - .env
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
    ports:
      - 10002:8080
    expose:
      - 8080
